### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by tfreedman** [DarwinAwardWinner/transfercoder#2]
Just had transfercoder crash while running a job:

INFO:transfercoder:Transcoding: "/Volumes/Music/Tagged/Martin O'Donnell & Michael Salvatori/Halo 2, Volume 1/01 Martin O'Donnell & Michael Salvatori - Halo Theme Mjolnir Mix.flac" -> "/private/var/folders/mx/7tw2ndkd5xx236fz2mr0z9km0000gn/T/transfercode_z5ekk692/01 Martin O'Donnell & Michael Salvatori - Halo Theme Mjolnir Mix_bzsjn7_m.ogg"
Traceback (most recent call last):
  File "/usr/local/bin/transfercoder", line 279, in main
  File "/usr/local/lib/python3.6/site-packages/transfercoder/__init__.py", line 383, in transfer
  File "/usr/local/lib/python3.6/site-packages/transfercoder/__init__.py", line 347, in copy
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 120, in copyfile
OSError: [Errno 24] Too many open files: '/Volumes/Music/Tagged/Miku Hatsune/初音ミク 5thバースデー ベスト ~impacts~/Various - 初音ミク 5thバースデー ベスト ～impacts～.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/transfercoder", line 335, in <module>
  File "/usr/local/bin/transfercoder", line 107, in plac_call_main
  File "/usr/local/lib/python3.6/site-packages/plac_core.py", line 328, in call
  File "/usr/local/lib/python3.6/site-packages/plac_core.py", line 207, in consume
  File "/usr/local/bin/transfercoder", line 281, in main
UnboundLocalError: local variable 'fname' referenced before assignment

**Comment by DarwinAwardWinner** [comment]
Can you give me an estimate of how many music files/albums were processed before hitting this error?

**Comment by tfreedman** [comment]
My music library is around 400GB, and this error occurs decently far through the library. My guess is that this happens well over 100GB into it, because the artist names aren't starting with A.

Also, I've noticed another problem with transfercoder, where disk space on my desktop slowly disappears (it's writing to a temp folder which is cleared by rebooting, but not until I reboot).

**Comment by tfreedman** [comment]
For the free space bug:

$ du -h | grep transfercode
 57G	./transfercode_jgn_3mhk
 67G	./transfercode_mma3lbc0

The source and destination folders are located on a network volume, so there shouldn't be lots of space occupied by temp files on my local SSD.

For too many open files: 

$ cat output.txt | grep INFO:transfercoder:Transcoding | wc -l
    4851

$ cat output.txt | grep 'Too many open files' | wc -l
   16828

**Comment by DarwinAwardWinner** [comment]
Ok, I have a guess as to what is happening. The way transfercoder works, each file is first transcoded to a temp file (if it needs transcoding) and then copied to its final destination, and the temp files is deleted. These steps happen in parallel, so that it can be transcoding one (or more) files while it is copying another file. Usually, copying is faster than transcoding, so the copying step is always ready for the next transcoded temp file. 

However, you mentioned your files were on a remote file system, which raises the possibility that transcoding might actually be faster than copying. In this case, the transcoding step will start getting ahead of of the copying step, generating temp files faster than they can be copied to the remote filesystem. As a result, temp files will accumulate, and since multiprocessing uses open filehandles to coordinate between parallel Python processes, open file handles also accumulate. This explains both the excessive disk usage and the "too many open files" error.

The workaround is to use `-j 0` to force transfercoder not to use parallel operation (note that this is not the same as `-j 1`). The real fix is for me to find a better way to do parallel operation that allows the transcode operation to pause and wait for the file-copying operation to catch up.

**Comment by tfreedman** [comment]
So I ran it and it succeeded, but there's a /slight/ problem with the output:
$transfercoder -j 0 -i flac,wav,alac,wma -o ogg -z -D -f /Volumes/Music/Tagged/ /Volumes/Music/Phone/

Tagged folder size: 353GB
Phone folder size: 349GB

$ ls -al
total 581993
drwxr-xr-x  1 tyler  staff       772 24 Sep 02:37 .
drwxr-xr-x  1 tyler  staff       264 26 Sep 01:39 ..
-rwxr-xr-x  1 tyler  staff  17715270 24 Sep 02:36 01 Hand Covers Bruise.ogg
-rwxr-xr-x  1 tyler  staff  28297535 24 Sep 02:37 02 In Motion.ogg
-rwxr-xr-x  1 tyler  staff  16680210 24 Sep 02:36 03 A Familiar Taste.ogg
-rwxr-xr-x  1 tyler  staff   4799077 24 Sep 02:36 04 It Catches Up With You.ogg
-rwxr-xr-x  1 tyler  staff  22969886 24 Sep 02:36 05 Intriguing Possibilities.ogg
-rwxr-xr-x  1 tyler  staff  11579970 24 Sep 02:36 06 Painted Sun in Abstract.ogg
-rwxr-xr-x  1 tyler  staff  12903706 24 Sep 02:36 07 3_14 Every Night.ogg
-rwxr-xr-x  1 tyler  staff  22289078 24 Sep 02:36 08 Pieces Form the Whole.ogg
-rwxr-xr-x  1 tyler  staff  21363399 24 Sep 02:36 09 Carbon Prevails.ogg
-rwxr-xr-x  1 tyler  staff  18443728 24 Sep 02:36 10 Eventually We Find Our Way.ogg
-rwxr-xr-x  1 tyler  staff   3738625 24 Sep 02:36 11 Penetration.ogg
-rwxr-xr-x  1 tyler  staff  11635137 24 Sep 02:37 12 In the Hall of the Mountain King.ogg
-rwxr-xr-x  1 tyler  staff  24431295 24 Sep 02:36 13 On We March.ogg
-rwxr-xr-x  1 tyler  staff  12010659 24 Sep 02:37 14 Magnetic.ogg
-rwxr-xr-x  1 tyler  staff  15699538 24 Sep 02:36 15 Almost Home.ogg
-rwxr-xr-x  1 tyler  staff   5904090 24 Sep 02:36 16 Hand Covers Bruise (reprise).ogg
-rwxr-xr-x  1 tyler  staff  16091752 24 Sep 02:36 17 Complication With Optimistic Outcome.ogg
-rwxr-xr-x  1 tyler  staff  16057440 24 Sep 02:36 18 The Gentle Hum of Anxiety.ogg
-rwxr-xr-x  1 tyler  staff  15325549 24 Sep 02:36 19 Soft Trees Break the Fall.ogg
-rwxr-xr-x  1 tyler  staff      2222 23 Sep 05:35 The Social Network .cue
-rwxr-xr-x  1 tyler  staff      7679 23 Sep 05:35 Trent Reznor and Atticus Ross - The Social Network .log
-rwxr-xr-x  1 tyler  staff     27680 23 Sep 05:35 cover.jpg

$ file 02\ In\ Motion.ogg
02 In Motion.ogg: Ogg data, FLAC audio

**Comment by DarwinAwardWinner** [comment]
If I'm understanding correctly, the output files are ogg, but contain FLAC audio data rather than Vorbis. If so, that's very weird. The majority of my music is FLAC, and it gets transcoded to Ogg Vorbis just fine (i.e. not Ogg FLAC). In fact, for ogg output, transfercoder specifically tells ffmpeg to encode in Vorbis (using `-codec:a libvorbis`), so I can't imagine why you would be getting output files without any other audio encoding. Can you run transfercoder in verbose mode on just a few files? It should print out the exact ffmpeg command it's using to do each transcode.

**Comment by tfreedman** [comment]
$ transfercoder -v -i flac,wav,alac,wma -o ogg -z -D ~/Desktop/Source/ ~/Desktop/Destination/ > output.txt 2>&1
[output.txt](https://github.com/DarwinAwardWinner/transfercoder/files/1332209/output.txt)

**Comment by DarwinAwardWinner** [comment]
Ok, there was a bug where the default encoder options were not used. If you check the log you posted, you'll see that transfercoder reports that it's going to use the default encoder options, but these options do not appear in any of the ffmpeg commands later in the log. I've fixed the problem in 9c97372, so please update to the latest master and try again.

Also, it seems that Homebrew builds ffmpeg without libvorbis support by default, so after updating, you're likely to get an error from ffmpeg about libvorbis being an unknown encoder. To fix that, you'll need to do something like `brew reinstall ffmpeg --with-libvorbis`.

Lastly, an update on the parallel issue: I don't think I know how to fix it properly. I've found a solution that seems to work (see [here](https://stackoverflow.com/questions/46396784/can-i-tell-pythons-multiprocessing-pool-not-to-get-too-far-ahead/46396875#46396875)), but it falls apart pretty badly as soon as anything unexpected happens (execptions thrown, Control+C pressed, etc.). It seems to me that Python's multiprocessing primitives are almost impossible to use correctly. So, for the forseeable future, the solution is to use `-j0`.

**Comment by DarwinAwardWinner** [comment]
I believe the "too many open files" issue has been fixed in 91eed93. If you have any other remaining issues, please report them as new issues.
