### ISSUE TITLE
Not ALL tags get copied

### ISSUE THREAD

**Issue by thrdroom** [DarwinAwardWinner/transfercoder#4]
I tried to copy **ALL tags** from a flac file to a m4a(alac) file.
And some tags present in the flac file got lost. For example: "ISRC" "Replaygain" and "Publisher" Tag.

Can you add the option to the script to really copy **ALL** the tags from one file to the other? And i mean really **ALL TAGS** also Replaygain tags etc.
TIA

**Comment by DarwinAwardWinner** [comment]
The answer here is the same as in my other script: https://github.com/DarwinAwardWinner/copytags/issues/1#issuecomment-556413000

However, for the replaygain tags, I specifically [avoid](https://github.com/DarwinAwardWinner/transfercoder/blob/master/transfercoder/__init__.py#L133-L139) copying them, since my experience has been that replaygain tags from one file don't necessarily apply to the transcoded version of that file. Instead, I prefer to just re-run replaygain after transcoding.
